/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { formFieldProps } from "./components/form-field/form-field";
export { formFieldProps } from "./components/form-field/form-field";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface FormField {
        "htmlFor": formFieldProps['htmlFor'];
        "label": formFieldProps['label'];
    }
    interface PlayerForm {
    }
    interface PlayerTable {
    }
    interface ProspectData {
        "devTrait": 'elite' | 'star' | 'impact' | 'normal';
        "totalCaps": number;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFormFieldElement extends Components.FormField, HTMLStencilElement {
    }
    var HTMLFormFieldElement: {
        prototype: HTMLFormFieldElement;
        new (): HTMLFormFieldElement;
    };
    interface HTMLPlayerFormElement extends Components.PlayerForm, HTMLStencilElement {
    }
    var HTMLPlayerFormElement: {
        prototype: HTMLPlayerFormElement;
        new (): HTMLPlayerFormElement;
    };
    interface HTMLPlayerTableElement extends Components.PlayerTable, HTMLStencilElement {
    }
    var HTMLPlayerTableElement: {
        prototype: HTMLPlayerTableElement;
        new (): HTMLPlayerTableElement;
    };
    interface HTMLProspectDataElement extends Components.ProspectData, HTMLStencilElement {
    }
    var HTMLProspectDataElement: {
        prototype: HTMLProspectDataElement;
        new (): HTMLProspectDataElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "form-field": HTMLFormFieldElement;
        "player-form": HTMLPlayerFormElement;
        "player-table": HTMLPlayerTableElement;
        "prospect-data": HTMLProspectDataElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface FormField {
        "htmlFor"?: formFieldProps['htmlFor'];
        "label"?: formFieldProps['label'];
    }
    interface PlayerForm {
    }
    interface PlayerTable {
    }
    interface ProspectData {
        "devTrait"?: 'elite' | 'star' | 'impact' | 'normal';
        "totalCaps"?: number;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "form-field": FormField;
        "player-form": PlayerForm;
        "player-table": PlayerTable;
        "prospect-data": ProspectData;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "form-field": LocalJSX.FormField & JSXBase.HTMLAttributes<HTMLFormFieldElement>;
            "player-form": LocalJSX.PlayerForm & JSXBase.HTMLAttributes<HTMLPlayerFormElement>;
            "player-table": LocalJSX.PlayerTable & JSXBase.HTMLAttributes<HTMLPlayerTableElement>;
            "prospect-data": LocalJSX.ProspectData & JSXBase.HTMLAttributes<HTMLProspectDataElement>;
        }
    }
}
